import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner, { IBanner } from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import { IItem } from "../components/ProductItem";
import { IBlogItem } from "../components/BlogItem";
export const API_KEY = "http://localhost:5001";
interface IHome {
  banner: IBanner;
  featuredProducts: IItem[];
  blogItem: IBlogItem[];
}
const Home: NextPage<IHome> = ({ banner, featuredProducts, blogItem }) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner preTitle={banner.preTitle} title={banner.title} />

      <CategoryPicker />

      <FeaturedProducts featuredProducts={featuredProducts} />

      <FeaturedBlogs blogs={blogItem} />
    </>
  );
};

export default Home;

export const getStaticProps:GetStaticProps = async () => {
  try {
    const resBanner = await fetch(API_KEY + "/banner_content");
    const banner = await resBanner.json();
    const resFeatured = await fetch(API_KEY + "/products/?_limit=4");
    const featuredProducts = await resFeatured.json();
    const resBlog = await fetch(API_KEY + "/blogs/?_limit=3");
    const blogItem = await resBlog.json();
    return {
      props: {
        banner,
        featuredProducts,
        blogItem,
      },
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return {
      props: {
        banner: {},
        featuredProducts: [],
        blogItem: [],
      },
    };
  }
};
